import type { Metadata } from "next";
import { cookies } from "next/headers";
import { AppHeaderNav } from "@/app/AppHeaderNav";
import { listCompanies } from "@/lib/companies-repo";
import {
  countPendingUploadQueueItemsByCompanyId,
} from "@/lib/invoice-uploads-repo";
import {
  ACTIVE_COMPANY_COOKIE_NAME,
  parseActiveCompanyId,
} from "@/lib/active-company";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const companies = listCompanies();
  const cookieStore = await cookies();
  const activeCompanyId = parseActiveCompanyId(
    cookieStore.get(ACTIVE_COMPANY_COOKIE_NAME)?.value,
  );
  const activeCompany = companies.find((company) => company.id === activeCompanyId) ?? null;
  const pendingInboxCount = activeCompany
    ? countPendingUploadQueueItemsByCompanyId(activeCompany.id)
    : null;

  return (
    <html lang="en">
      <body className="antialiased">
        <AppHeaderNav
          hasActiveCompany={activeCompany !== null}
          activeCompanyName={activeCompany?.name ?? null}
          pendingInboxCount={pendingInboxCount}
        />
        {children}
      </body>
    </html>
  );
}
